## Numpy sum

In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
sum(a), a.sum()

(array([4, 6]), 10)

In [3]:
a.sum(axis = 0), a.sum(axis = 1)

(array([4, 6]), array([3, 7]))

## concatenate

In [6]:
# vertical, horizon
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.vstack([a, b]), '\n\n', np.hstack([a, b]))
# vertical은 2차원으로 변함

[[1 2 3]
 [2 3 4]] 

 [1 2 3 2 3 4]


In [18]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
print(np.concatenate((a, b), axis = 0), '\n\n', np.concatenate((a, b), axis = 1))

[[1 2 3]
 [2 3 4]] 

 [[1 2 3 2 3 4]]


## broadcasting

In [22]:
a + 3 # 이 외 모든 사칙연산 가능 

array([[4, 5, 6]])

In [25]:
a[a >1]

array([2, 3])

## Where

In [26]:
np.where(a > 0, 3, 2) # True = 3, False = 2

array([[3, 3, 3]])

In [32]:
c = np.where(a > 1); c

(array([0, 0], dtype=int64), array([1, 2], dtype=int64))

In [34]:
a = np.arange(10)
a, np.where(a > 5)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (array([6, 7, 8, 9], dtype=int64),))

## Argmax & Argmin

In [38]:
w = np.arange(10)
np.argmax(w), np.argmin(w)

(9, 0)

In [44]:
a = np.array([[1, 2, 3], [3, 2, 1], [1, 3, 2]])
print(a,'\n\n', np.argmax(a), '\n\n', np.argmax(a, axis = 1), '\n\n', np.argmax(a, axis = 0))

[[1 2 3]
 [3 2 1]
 [1 3 2]] 

 2 

 [2 0 1] 

 [1 2 0]


## Series operation

In [47]:
import pandas as pd

In [52]:
s1 =pd.Series(range(1, 6), index = list('abced'))
s2 = pd.Series(range(5, 11), index = list('bcedef'))
print(s1.add(s2),'\n\n', s1 + s2)

a     NaN
b     7.0
c     9.0
d    13.0
e    11.0
e    13.0
f     NaN
dtype: float64 

 a     NaN
b     7.0
c     9.0
d    13.0
e    11.0
e    13.0
f     NaN
dtype: float64


In [53]:
s1.add(s2, fill_value = 0)

a     1.0
b     7.0
c     9.0
d    13.0
e    11.0
e    13.0
f    10.0
dtype: float64

In [54]:
s1 = pd.Series(np.arange(10))
s1.map(lambda x: x ** 2).head(5)

0     0
1     1
2     4
3     9
4    16
dtype: int64