In [3]:
import numpy as np
# data
samples = ['The cat sat on the mat.', 'The dog ate my homework.']

# 데이터 모든 토큰의 인덱스를 구축
token_index = {}

for sample in samples:
  # split으로 떼어냄. 실전에서는 특수문자 다 사용함.
  print(sample)
  for word in sample.split():
    # token_index안에 word가 없을 경우(중복 허용 안 하는듯)
    if word not in token_index:
      # index 0은 관례상 사용하지 않는다고 함
      token_index[word] = len(token_index) + 1

  print(token_index)

The cat sat on the mat.
{'The': 1, 'cat': 2, 'sat': 3, 'on': 4, 'the': 5, 'mat.': 6}
The dog ate my homework.
{'The': 1, 'cat': 2, 'sat': 3, 'on': 4, 'the': 5, 'mat.': 6, 'dog': 7, 'ate': 8, 'my': 9, 'homework.': 10}


In [5]:
# 샘플을 벡터로 변환
# 각 샘플당 max_length까지만 단어로 사용
max_length = 10
# len(samples) = 2, max_leng = 10, max(token_index.value()) + 1 = 10 + 1 = 11
results = np.zeros((len(samples), max_length, max(token_index.values()) + 1))
print(results)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [13]:
len(samples), token_index.values()

(2, dict_values([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

In [10]:
max(token_index.values()) + 1

11

In [21]:
token_index.get('The')

1

In [22]:
for i, sample in enumerate(samples):
  for j, word in list(enumerate(sample.split()))[:max_length]:
    print(j, word)
    index = token_index.get(word) # token_index.get(The) = 1
    results[i, j, index] = 1.

0 The
1 cat
2 sat
3 on
4 the
5 mat.
0 The
1 dog
2 ate
3 my
4 homework.


In [20]:
results

array([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0

In [23]:
# 문자 수준 one hot encoding

import string
characters = string.printable
characters # 모든 출력 가능한 아스키 문자

'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c'

In [29]:
len(characters)

100

In [25]:
token_index = dict(zip(characters, range(1, len(characters) + 1))); token_index

{'\t': 96,
 '\n': 97,
 '\x0b': 99,
 '\x0c': 100,
 '\r': 98,
 ' ': 95,
 '!': 63,
 '"': 64,
 '#': 65,
 '$': 66,
 '%': 67,
 '&': 68,
 "'": 69,
 '(': 70,
 ')': 71,
 '*': 72,
 '+': 73,
 ',': 74,
 '-': 75,
 '.': 76,
 '/': 77,
 '0': 1,
 '1': 2,
 '2': 3,
 '3': 4,
 '4': 5,
 '5': 6,
 '6': 7,
 '7': 8,
 '8': 9,
 '9': 10,
 ':': 78,
 ';': 79,
 '<': 80,
 '=': 81,
 '>': 82,
 '?': 83,
 '@': 84,
 'A': 37,
 'B': 38,
 'C': 39,
 'D': 40,
 'E': 41,
 'F': 42,
 'G': 43,
 'H': 44,
 'I': 45,
 'J': 46,
 'K': 47,
 'L': 48,
 'M': 49,
 'N': 50,
 'O': 51,
 'P': 52,
 'Q': 53,
 'R': 54,
 'S': 55,
 'T': 56,
 'U': 57,
 'V': 58,
 'W': 59,
 'X': 60,
 'Y': 61,
 'Z': 62,
 '[': 85,
 '\\': 86,
 ']': 87,
 '^': 88,
 '_': 89,
 '`': 90,
 'a': 11,
 'b': 12,
 'c': 13,
 'd': 14,
 'e': 15,
 'f': 16,
 'g': 17,
 'h': 18,
 'i': 19,
 'j': 20,
 'k': 21,
 'l': 22,
 'm': 23,
 'n': 24,
 'o': 25,
 'p': 26,
 'q': 27,
 'r': 28,
 's': 29,
 't': 30,
 'u': 31,
 'v': 32,
 'w': 33,
 'x': 34,
 'y': 35,
 'z': 36,
 '{': 91,
 '|': 92,
 '}': 93,
 '~': 94

In [28]:
[i for i in zip(characters, range(1, len(characters) + 1))]

[('0', 1),
 ('1', 2),
 ('2', 3),
 ('3', 4),
 ('4', 5),
 ('5', 6),
 ('6', 7),
 ('7', 8),
 ('8', 9),
 ('9', 10),
 ('a', 11),
 ('b', 12),
 ('c', 13),
 ('d', 14),
 ('e', 15),
 ('f', 16),
 ('g', 17),
 ('h', 18),
 ('i', 19),
 ('j', 20),
 ('k', 21),
 ('l', 22),
 ('m', 23),
 ('n', 24),
 ('o', 25),
 ('p', 26),
 ('q', 27),
 ('r', 28),
 ('s', 29),
 ('t', 30),
 ('u', 31),
 ('v', 32),
 ('w', 33),
 ('x', 34),
 ('y', 35),
 ('z', 36),
 ('A', 37),
 ('B', 38),
 ('C', 39),
 ('D', 40),
 ('E', 41),
 ('F', 42),
 ('G', 43),
 ('H', 44),
 ('I', 45),
 ('J', 46),
 ('K', 47),
 ('L', 48),
 ('M', 49),
 ('N', 50),
 ('O', 51),
 ('P', 52),
 ('Q', 53),
 ('R', 54),
 ('S', 55),
 ('T', 56),
 ('U', 57),
 ('V', 58),
 ('W', 59),
 ('X', 60),
 ('Y', 61),
 ('Z', 62),
 ('!', 63),
 ('"', 64),
 ('#', 65),
 ('$', 66),
 ('%', 67),
 ('&', 68),
 ("'", 69),
 ('(', 70),
 (')', 71),
 ('*', 72),
 ('+', 73),
 (',', 74),
 ('-', 75),
 ('.', 76),
 ('/', 77),
 (':', 78),
 (';', 79),
 ('<', 80),
 ('=', 81),
 ('>', 82),
 ('?', 83),
 ('@', 84),
 

In [32]:
max_length = 50
# 2, 50, 101
results = np.zeros((len(samples), max_length, max(token_index.values()) + 1))
for i, sample in enumerate(samples):
  for j, character in enumerate(sample[:max_length]):
    index = token_index.get(character)
    results[i, j, index] = 1.
results

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [78]:
# 케라스를 사용한 단어수준의 one hot encoding
from keras.preprocessing.text import Tokenizer

# 가장 빈도가 높은 1천 개만 선택하도록
tokenizer = Tokenizer(num_words = 1000)
tokenizer.fit_on_texts(samples) # 단어 인덱스 구축

# 문자열을 정수 인덱스의 리스트로 변환
sequences = tokenizer.texts_to_sequences(samples)
sequences

# texts_to_matrix는 sample을 texts_to_sequence를 하고 sequences_to_matrix 한 것과 같다

[[1, 2, 3, 4, 1, 5], [1, 6, 7, 8, 9]]

In [79]:
tokenizer.sequences_to_matrix(sequences)

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [43]:
# 직접 one hot 이진 벡터 표현을 얻을 수 있음
one_hot_results = tokenizer.texts_to_matrix(samples, mode = 'binary')
one_hot_results.shape, one_hot_results

((2, 1000), array([[0., 1., 1., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.]]))

In [46]:
one_hot_results[:, :30]

array([[0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
word_index = tokenizer.word_index
print('Found %s unique tokens' % len(word_index))
print(word_index)

Found 9 unique tokens
{'the': 1, 'cat': 2, 'sat': 3, 'on': 4, 'mat': 5, 'dog': 6, 'ate': 7, 'my': 8, 'homework': 9}


## One hot hazing

In [49]:
word

'homework.'

In [50]:
hash(word)

7713838377624052780

In [52]:
3 % 2

1

In [73]:
hash(word) % 1000

780

In [70]:
# 1천 개 이상이 있다면 해싱 충돌이 늘어나고 인코딩의 정확도가 감소
dimensionality = 1000
max_length = 10

results = np.zeros((len(samples), max_length, dimensionality))
for i, sample in enumerate(samples):
  for j, word in list(enumerate(sample.split()))[:max_length]:
    # 각 단어를 해싱해서 0, 1천 사이 랜덤 정수 인덱스로 변환
    index = abs(hash(word)) % dimensionality
    results[i, j, index] = 1.
    print(i, j, index)

0 0 243
0 1 134
0 2 271
0 3 462
0 4 609
0 5 603
1 0 243
1 1 632
1 2 713
1 3 481
1 4 780


In [71]:
results[1, 4, 770:785]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])